server:
  port: 7070
application:
  version: 1.0
  formatted-version: (v1.0)
  name: rabbitproto
nuvola:
  avaya:
    queueAcd1: avaya1.queue
    queueAcd2: avaya2.queue
  key:
    userKey: user.*
    userToKey: user.to.*
  exchange:
    topicUser: NEW_USER_EXCHANGE
---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://localhost/proto
    username: dbuser
    password: dbpass
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
